server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    pipeline_stages:
      - docker: { }
      - static_labels:
          job: promtail
    relabel_configs:
      - source_labels:
        - __meta_docker_container_name
        regex: '/(.*)'
        target_label: container
  - job_name: services
    static_configs:
      - targets:
          - localhost
        labels:
          job: services
          __path__: /var/log/*.log

  #       filters:
  #         - name: label
  #           values: ["logging=promtail"]
  #   relabel_configs:
  #     - source_labels: ["__meta_docker_container_name"]
  #       regex: "/(.*)"
  #       target_label: "container"
  #     - source_labels: ["__meta_docker_container_log_stream"]
  #       target_label: "logstream"
  #     - source_labels: ["__meta_docker_container_label_logging_jobname"]
  #       target_label: "job"
  #     - source_labels: [log]
  #       separator: ';'
  #       regex: '^{.*"message":"(.*?)".*$'
  #       target_label: message
  #       replacement: '$1'
